# Generated by Django 4.1.13 on 2023-11-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePicture', models.ImageField(upload_to='profile_pictures/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.userprofile')),
            ],
        ),
    ]
